url: https://RamzziSudip.github.io/agency-jekyll-theme
baseurl: /

# Site settings
title: Find Yourself!
email: sudiproy20yo@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Sudip Roy
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
    url: https://www.twitter.com/SudipRo83430078
    - title: facebook
    url: https://www.facebook.com/profile.php?id=100009310496231
    - title: instagram
    url: https://www.instagram.com/sudip.co/

- name: Sudip Roy
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
    url: https://www.twitter.com/SudipRo83430078
    - title: facebook
    url: https://www.facebook.com/profile.php?id=100009310496231
    - title: instagram
    url: https://www.instagram.com/sudip.co/

- name: Sudip Roy
  pic: 3
  position: Lead Developer
  social:
  - title: twitter
    url: https://www.twitter.com/SudipRo83430078
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100009310496231
  - title: instagram
    url: https://www.instagram.com/sudip.co/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://www.twitter.com/SudipRo83430078
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100009310496231
  - title: instagram
    url: https://www.instagram.com/sudip.co/
  - title: bitbucket 
    url: http://bitbucket.org/Gray_Solution
  - title: github
    url: https://github.com/RamzziSudip/


# Postal address (add as many lines as necessary)
address:
  - line: India, Westbengal, Hooghly
  - line: Chinsurah, Chatterjee Bagan 712102

# Build settings
markdown: kramdown
permalink: pretty
